# Generated by Django 3.0.7 on 2020-06-21 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsplugin_contact_plus', '0004_auto_20170410_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactplus',
            name='recipient_email',
            field=models.EmailField(default='', max_length=254, verbose_name='Email of recipients'),
        ),
        migrations.AlterField(
            model_name='contactplus',
            name='template',
            field=models.CharField(choices=[('cmsplugin_contact_plus/contact.html', 'contact.html')], default='cmsplugin_contact_plus/contact.html', editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='contactrecord',
            name='date_processed',
            field=models.DateTimeField(blank=True, help_text='Date the Record was processed.', null=True),
        ),
    ]
